### ISSUE TITLE
Add https://github.com/copperspice/cs_signal/issues/6

### ISSUE THREAD

**Issue by Ultrafeel** [NoAvailableAlias/signal-slot-benchmarks#11]

**Comment by NoAvailableAlias** [comment]
I've starting looking into this lib and will work on adding it to the rework branch.
However, the release of the rework branch will coincide with the release of the reworked nano-signal-slot so it might be delayed further than it already has been.

Edit: will run just the newly integrated lib and will patch the msvc results page soon. (rework branch)
Edit: looks like i will need to open a threading issue for this lib...
Edit: i have opened [this issue](https://github.com/copperspice/cs_signal/issues/7) due to encountering a possible thread safety issue.

**Comment by NoAvailableAlias** [comment]
Added a single threaded integration of cs_signal into the rework branch.
This issue will be closed once pushed.

**Comment by NoAvailableAlias** [comment]
Hmm, forgot to add a close to this to the PR.
