### ISSUE TITLE
CMake fails as Boost.Signals has been removed from latest versions of Boost.

### ISSUE THREAD

**Issue by i42output** [NoAvailableAlias/signal-slot-benchmarks#15]
You should be using Boost.Signals2 instead.

**Comment by NoAvailableAlias** [comment]
Indeed, I really need to get an appropriate dev environments up and running. Does this unified diff look correct?

![diff](https://user-images.githubusercontent.com/6961420/70377986-0e06e180-18e9-11ea-8d9c-2d54c20dddb2.PNG)

(std::filesystem is now used instead of boost::filesystem)

Ok nevermind then, signals2 is header only.

**Comment by NoAvailableAlias** [comment]
boost signals removed from cmake. thanks for reporting this
