### ISSUE TITLE
neosigslot

### ISSUE THREAD

**Issue by i42output** [NoAvailableAlias/signal-slot-benchmarks#2]
Hi!

The performance of my lib looks pretty poor.. did you try benchmarking with the single threaded version (no locking policy specialization) like with the other single threaded libs?

/Leigh

**Comment by NoAvailableAlias** [comment]
Hello, for the implementations tested that are capable of either thread safe / non-safe, I have not tested them under single thread configurations. I do, however, delineate which implementations are thread safe in the results. I do have plans to refactor the benchmarks and hoist the thread safe implementations into a new multithreaded benchmark. For the time being, I'll have to rerun the benchmark for these special cases and provide the results until the new benchmark is created.

**Comment by NoAvailableAlias** [comment]
I ended up having to remove your library from the rework branch since std::auto_ptr has reached the end of life.

If you have an up to date version could you respond back with a link to it and I'll get it re-added.

**Comment by i42output** [comment]
neosigslot is part of "neolib" which can be found at https://github.com/i42output/neolib. "neolib" migrated to std::unique_ptr some time ago.

**Comment by i42output** [comment]
I have just updated it to use unordered_map/set and std::recursive_mutex.

**Comment by i42output** [comment]
Just changed neosigslot to default to single threaded which should push it up the table.

**Comment by NoAvailableAlias** [comment]
Got it, guess i should have checked your user page first. I'll get it added next thing i push to the rework branch.

Right now i'm failing at making nano-signal-slot thread-safe so don't know when rework will be ready for release though.

I'm going separate thread-safe libs from single thread libs in the upcoming release as well.

**Comment by NoAvailableAlias** [comment]
Hello, I have added two "Nls" benchmark classes based on your locking policies.
I have not run the benchmarks at an adequate sample size (takes several hours) but I would checkout the rework branch for yourself and try to investigate the results I am seeing...

Also, I had to disambiguate the std::placeholders in signal.hpp in order to scare boost::placeholders away.

**Comment by i42output** [comment]
Just to let you know "neosigslot" is now at v2.0.  I have thrown out the entire existing implementation (which was old in the pre-C++11 tooth) and it now uses an entirely new event system moved over from my other library "neoGFX" (a new cross-platform C++ GUI library).  The old neosigslot API is deprecated but should still work.

**Comment by NoAvailableAlias** [comment]
I haven't looked through your new implementation enough to tell if it changed the public interface or not. If there were no changes then integration into the benchmarks shouldn't be to tremendous.

For now I have closed the issue since the original issue has been resolved with the latest push to master.

**Comment by i42output** [comment]
Hi.  I have cloned your repo and got it working with the latest version; it is no longer at the bottom of table... :/

**Comment by NoAvailableAlias** [comment]
I'll get it updated this week. I take it there isn't anything major needed in the benchmark_nls classes?

**Comment by i42output** [comment]
The biggest thing is it is now dependent on more .cpps from the neolib library.

**Comment by NoAvailableAlias** [comment]
that shouldn't be a problem. as long as the public interface didn't change. i'll just have to remember to add all of them to the cmakelist because i don't even have a linux environment to test with

**Comment by i42output** [comment]
I have just added neolib::event_system::set_multi_threaded() and set_single_threaded() to modify threading model; the locking policies are no longer used.

**Comment by NoAvailableAlias** [comment]
ok i'm going to have to add a new method to the benchmark interface to support "benchmark init". otherwise i won't be able to run neolib signal in both multi-thread vs single-thread in the same run.

will still probably be this week. unless my resolution doesn't work or i die half way through adding this method to all benchmark hpp/cpp

**Comment by i42output** [comment]
Just to let you know that I've just pushed a new commit to get single/multi-threaded selection working properly; the commit last night had problems.

**Comment by NoAvailableAlias** [comment]
Let me know when you have neolib ready for integration. I've added support to all benchmark classes for "benchmark initialize" which will allow for runtime policy changes, but I have yet to pull the latest neolib changes.

**Comment by i42output** [comment]
Should be ready now.

**Comment by i42output** [comment]
Hold that.. Just spotted a big mistake; will fix tonight.

**Comment by i42output** [comment]
Hi again.  neolib is ready to be pulled now.

**Comment by NoAvailableAlias** [comment]
well i updated my visual studio before finally integrating neolib::event. big mistake. now almost half the libs won't compile. heck now nano-signal-slot standalone wont compile and once the issue was resolved then the unit tests were failing to compile internally due to a C3688... im not wasting my time downgrading visual studio. it could take a little while to get the new neolib results.

**Comment by NoAvailableAlias** [comment]
ok, appears the issue is with the Visual Studios \fpermissive- flag. However, i had to add the _SILENCE_ALL_CXX17_DEPRECATION_WARNINGS define because neolib is using the deprecated (in c++17) std::allocator class template. 

Lastly, the results are now better. However, it seems there is a bug in ~basic_lifetime() and it crashes at the very end of the benchmarks. Maybe it is due to my integration. Is there anything special I must do at the end of main?

![image](https://user-images.githubusercontent.com/6961420/44185784-96a1b300-a0e3-11e8-8914-0fc333e6ed08.hide.png)

**Comment by i42output** [comment]
Do you have a branch I can pull so I can debug the crash?

**Comment by NoAvailableAlias** [comment]
Yes, I have just pushed the "rework" branch with my local changes. Additionally, only neolib benchmarks are enabled for easier debugging.

Edit: Also noticed that the single threaded policy doesn't appear to be taking effect? The results for singled threaded mode is lower than the multi threaded mode.

Edit: Also I had to change a handful of includes due to not configuring include directories.

**Comment by i42output** [comment]
I will try pulling your branch tonight however I have just committed some fixes related to threading which you might want to try in the meantime. :D

**Comment by i42output** [comment]
I've built and ran the VS2017 release build of rework + latest neolib and there doesn't appear to be any problems...

**Comment by NoAvailableAlias** [comment]
I've pulled the changes and all seems to be good now. I'll push to master when I get the new results run. Going forward there will be no maintenance on most of the libs. There are a handful that are ancient that I might want to re-pull from their respective repos but not many will get that treatment. If you need new results ran I recommend forking the project and making a pull request after you're satisfied with the results.

**Comment by i42output** [comment]
Thanks! It is wasn't pleasant being bottom of a leaderboard! :D

**Comment by NoAvailableAlias** [comment]
Just a heads up. Going to have to temporarily remove the threadsafe neolib test at least in the rework branch due to the following:

![neolib](https://user-images.githubusercontent.com/6961420/45845539-6dcc9900-bcf3-11e8-821e-5a0758534f83_.PNG)

**Comment by i42output** [comment]
The version of neolib event you are using appears to be dated 18 august; there have been lots of changes since then mainly to do with thread safety.

**Comment by NoAvailableAlias** [comment]
Indeed, I am a bit behind. I have updated and will update the results in the morning.

**Comment by NoAvailableAlias** [comment]
So I added the ability to discard the "construct" score in final scoring, (due to outside influences), and it appears that [completely changes score ordering results](https://plot.ly/%7ENoAvailableAlias/1/).

Just wanted to give you a heads up before the rework branch gets pushed soon.

(note that the legend is ordered to the previous results when the "construct" score was part of the final score)

**Comment by i42output** [comment]
Thanks for tweaking your benchmark methodology to make my lib look bad again. :)

**Comment by i42output** [comment]
Your rework branch fails to compile code for your library so I am unable to investigate further improvements at this time...

**Comment by NoAvailableAlias** [comment]
I just cloned to desktop the rework branch and have no issues building that in visual studio 2017 community for both debug and release. Can you provide more information?

I have not tested is the cmake file.

**Comment by i42output** [comment]
1>------ Build started: Project: signal-slot-benchmarks, Configuration: Release x64 ------
1>cl : Command line warning D9002: ignoring unknown option '/arch:IA32'
1>benchmark_nss.cpp
1>benchmark_nss_v2.cpp
1>d:\code\signal-slot-benchmarks\benchmark\lib\noavailablealias\nano-signal-slot-v2x\nano_observer.hpp(122): error C2280: 'std::lock_guard<Nano::TS_Policy<`anonymous-namespace'::Mutex>>::lock_guard(const std::lock_guard<Nano::TS_Policy<`anonymous-namespace'::Mutex>> &)': attempting to reference a deleted function
1>c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.14.26428\include\mutex(526): note: see declaration of 'std::lock_guard<Nano::TS_Policy<`anonymous-namespace'::Mutex>>::lock_guard'
1>d:\code\signal-slot-benchmarks\benchmark\lib\noavailablealias\nano-signal-slot-v2x\nano_observer.hpp(121): note: while compiling class template member function 'void Nano::Observer<`anonymous-namespace'::Policy>::disconnect_all(void) noexcept'
1>d:\code\signal-slot-benchmarks\benchmark\lib\noavailablealias\nano-signal-slot-v2x\nano_observer.hpp(147): note: see reference to function template instantiation 'void Nano::Observer<`anonymous-namespace'::Policy>::disconnect_all(void) noexcept' being compiled
1>d:\code\signal-slot-benchmarks\benchmark\hpp\benchmark_nss_v2.hpp(17): note: see reference to class template instantiation 'Nano::Observer<`anonymous-namespace'::Policy>' being compiled
1>c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.14.26428\include\mutex(526): note: 'std::lock_guard<Nano::TS_Policy<`anonymous-namespace'::Mutex>>::lock_guard(const std::lock_guard<Nano::TS_Policy<`anonymous-namespace'::Mutex>> &)': function was explicitly deleted
1>benchmark_nss_v2_st.cpp
1>Generating Code...
1>Done building project "signal-slot-benchmarks.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

**Comment by NoAvailableAlias** [comment]
ok, so this is on coliru newest gcc:
http://coliru.stacked-crooked.com/a/9094c7b2ca154597
This is some msvc that is not in my current dev environment:
http://rextester.com/GBIF77032

So somehow in this test case the copy is not being elided it should be treated as rvalue in msvc.
(also I have not encountered this in my visual studio 15.8.0 although will update and see if that breaks)

**Comment by i42output** [comment]
I am running VS2017, 15.7.5. Going to update to latest VS2017 now.

**Comment by i42output** [comment]
Yes it builds fine with latest VS2017; sorry for the noise.
