### ISSUE TITLE
program use for build size metrics

### ISSUE THREAD

**Issue by delaitre** [NoAvailableAlias/signal-slot-benchmarks#5]
I am particularly interested on the size of the final binary.

I would have expected to find one program for each lib, and then taking the binary size of each of the binary. But I only see `benchmark.cpp` that build benchmark for all libs at once.

How did you get the numbers in the metrics section?

Cheers!

**Comment by NoAvailableAlias** [comment]
VisualStudio 2015 RC community was used at the time. If I recall correctly, due to the structure of the benchmark classes, each "signal library benchmark implementation" resided in their own respective computational unit (or CU). This resulted in individual DLLs being generated for each implementation. It is the size of these individual DLLs that are listed in the results.

Also, thanks for the push!
I have been absolutely absent due to no longer keeping up with c++ (I blame my job)...

**Comment by delaitre** [comment]
Yeah there are different object file for each generated. Maybe this should
be mentionned in the benchmark result document.
